language: rust

rust:
  - 1.19.0
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

env:
  global:
    - RUST_BACKTRACE=1

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
